### ISSUE TITLE
Priority not respected for multiple calls to `listenFor`

### ISSUE THREAD

**Issue by rlf** [InventivetalentDev/EventCallbacks#1]
The event priority is only assigned to the listener when the first event is registered in the event-map.

That means, multiple calls from the same plugin, for different priorities get the same priority as the first one.

```
EventCallbacks events = EventCallbacks.of(plugin);
events.listenFor(PlayerInteractEntityEvent.class, EventPriority.NORMAL, ...,);
events.listenFor(PlayerInteractEntityEvent.class, EventPriority.HIGH, ...,); // This will fire during NORMAL 
```

Additionally, the way the eventhandler iterates, if you add a listener during the eventcallback, it will fire the event immediately.

```
final EventCallbacks events = EventCallbacks.of(plugin);
events.listenFor(PlayerInteractEntityEvent.class, new PlayerEventCallback<PlayerInteractEntityEvent>(player) {
  @Override
  public void callPlayer(PlayerInteractEntityEvent event) {
    events.listenFor(PlayerInteractEntityEvent.class, new PlayerEventCallback...); // Will fire immediately
  }
});
```

**Comment by InventivetalentDev** [comment]
Fixed by https://github.com/InventivetalentDev/EventCallbacks/commit/ed22512215ce5e4748be8ad3e5c410ad12390e13 / https://github.com/InventivetalentDev/EventCallbacks/commit/0928958a368d5846b7a91e0bdceb6b8445bab021
